### ISSUE TITLE
Feature: Implement browser signing for HTTP signatures.

### ISSUE THREAD

**Issue by jojobii-arks** [musakui/fedi#2]
## Issue

- Taken from `TODO:` comment: implement browser signing.

https://github.com/musakui/fedi/blob/64c918675383ade2e358730c77eb1515bb666378/lib/hs/index.js#L52-L56

## Notes

- [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) could possibly be used to sign the input string. 
- Alternatively, a library such as [`god_crypto`](https://github.com/invisal/god_crypto) (this is only for Deno tho lol) can be used to sign the request (I've implemented it in [`jojobii/yafr-replica`](https://github.com/jojobii-arks/yafr-replica/blob/2c486efc452c2432a0a9559af6bb5bf1431da2d8/src/lib/utils/signatures.ts#L66-L72)
  - Having interop outside of Node by utilizing Web Crypto API would be greatly preferred. IDK if a `god_crypto` alternative exists via npm, but that'd be ideal.

**Comment by randName** [comment]
I actually left it out at first because I realized CORS would have prevented requests directly from the browser. But it seems like Deno uses the `browser` export in `package.json`? I couldn't find much concrete info. 

From my limited knowledge of Deno I know it supports a lot of web APIs so implementing signing (and even verification) using WebCrypto seems like a worthy cause

**Comment by randName** [comment]
experimental implementation in 6958121

**Comment by jojobii-arks** [comment]
stale; closing
